kind: pipeline
name: default

steps:
  - name: test
    image: python:3.6
    commands:
      - pip install -r requirements.txt
      - ./vgraph.py ./data/00.dat
      - "[ -e graph.png ]"
    when:
      event:
        - push
        - pull_request
